INSERT INTO {{ params.service_schema }}.{{ params.service_table }} SELECT DISTINCT * FROM s3(
    '{{ params.bucket_address }}dt={{ data_interval_end | ds }}/b={{ params.batch }}/{{ params.table_path }}/*.gz.parquet',
    '{{ conn.s3.extra_dejson.aws_access_key_id }}',
    '{{ conn.s3.extra_dejson.aws_secret_access_key }}',
    'Parquet',
    'app_id String,
        media_source String,
        date Date,
        agency String,
        campaign String,
        campaign_id String,
        adset String,
        adset_id String,
        ad String,
        ad_id String,
        channel String,
        geo String,
        site_id String,
        keywords String,
        timezone String,
        ad_account String,
        cost Float32,
        currency String,
        impressions UInt64,
        clicks UInt64,
        reported_clicks UInt64,
        re_engagements UInt64,
        re_attributions UInt64,
        original_cost Float32,
        original_currency String,
        reported_impressions UInt64,
        installs UInt64'
    )